### ISSUE TITLE
More duplication of code! 👯‍♂️

### ISSUE THREAD

**Issue by haydnba** [FACN4/Week-2-G-force-project#21]
https://github.com/FACN4/Week-2-G-force-project/blob/be973fdb439037fb73a6f3c8c2eab04957c71573/dom.js#L73

You are clearing the form input element here which is obviously very sensible, but there is no need to use `document.getElementById.....` again here - you already have access to this element in the `addTodoForm` variable!
👥👥👥

**Comment by tawfiknasser** [comment]
https://github.com/FACN4/Week-2-G-force-project/blob/be973fdb439037fb73a6f3c8c2eab04957c71573/style.css#L38

https://github.com/FACN4/Week-2-G-force-project/blob/be973fdb439037fb73a6f3c8c2eab04957c71573/style.css#L25

declaring twice the colour
